version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-test}
      MYSQL_USER: ${DATABASE_USER:-test}
      MYSQL_PASSWORD: ${DATABASE_PASS:-test}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  server:
    env_file:
      - .env
    build: 
      context: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '${APP_PORT:-3000}:${APP_PORT:-3000}'
volumes:
  my-db: